### ISSUE TITLE
Adversarial Supernet training

### ISSUE THREAD

**Issue by LiuJia68** [walkerning/aw_nas#46]
Dear author,

Thanks a lot for developing such a good framework. I am interested in adversarial robustness. Could you show me how to implement adversarial supernet training by using the plugins? Thanks a lot for your time.

Best wishes,
Jia

**Comment by LiuJia68** [comment]
When I run "awnas search cfgs/example_supernet_training.yaml --gpu 0 --save-every 50", it shows:
"aw_nas.utils.registry.RegistryError: No registry item dense_rob available in registry search_space."

**Comment by LiuJia68** [comment]
When I run "bash run_cfg.sh ../../plugins/robustness/cfgs/stagewise_predbased/search-multishoteval_stagewisess_fgsm_gates_2000M.yaml", I met the same error.

**Comment by walkerning** [comment]
Hi, thanks for your interests. Sorry for the late reply. You should follow [this](https://github.com/walkerning/aw_nas/tree/master/examples/research/multishot-robnas#environmental-setup) to setup this env. It is to link the python modules under `examples/plugins/robustness` to the plugin module (to be found by `awnas`).

**Comment by LiuJia68** [comment]
> Hi, thanks for your interests. Sorry for the late reply. You should follow [this](https://github.com/walkerning/aw_nas/tree/master/examples/research/multishot-robnas#environmental-setup) to setup this env. It is to soft link the python modules under `examples/plugins/robustness` to the plugin directory to be found by `awnas`. By default, the plugin directory is `${HOME}/awnas/plugins`, this position would be `${AWNAS_HOME}/plugins` if the `AWNAS_HOME` env variable is defined.

 Thank you for the reply and the problem above has been solved. However, when I "bash run_cfg.sh ../../plugins/robustness/cfgs/stagewise_predbased/search-multishoteval_stagewisess_fgsm_gates_2000M.yaml", I met ### **AssertionError** as follows:
 Traceback (most recent call last):
  File "/user/HS129/jl01890/miniconda3/envs/awnas/bin/awnas", line 33, in <module>
    sys.exit(load_entry_point('aw-nas', 'console_scripts', 'awnas')())
  File "/user/HS129/jl01890/miniconda3/envs/awnas/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/user/HS129/jl01890/miniconda3/envs/awnas/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/user/HS129/jl01890/miniconda3/envs/awnas/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/user/HS129/jl01890/miniconda3/envs/awnas/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/user/HS129/jl01890/miniconda3/envs/awnas/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/user/HS129/jl01890/aw_nas/aw_nas/main.py", line 230, in search
    trainer = _init_components_from_cfg(cfg, device)[-1]
  File "/user/HS129/jl01890/aw_nas/aw_nas/main.py", line 88, in _init_components_from_cfg
    rollout_type=rollout_type)
  File "/user/HS129/jl01890/aw_nas/aw_nas/main.py", line 115, in _init_component
    return cls(**addi_args)
  File "/user/HS129/jl01890/awnas/plugins/robustness/2_multi_evaluator.py", line 146, in __init__
    schedule_cfg,
  File "/user/HS129/jl01890/awnas/plugins/robustness/2_multi_evaluator.py", line 48, in __init__
    dataset, sub_wm, objective, **eva_cfg
  File "/user/HS129/jl01890/aw_nas/aw_nas/evaluator/mepa.py", line 502, in __init__
    mepa_as_surrogate)
  File "/user/HS129/jl01890/aw_nas/aw_nas/evaluator/mepa.py", line 1378, in _init_data_queues_and_hidden
    shuffle_indice_file=self.shuffle_indice_file)
  File "/user/HS129/jl01890/aw_nas/aw_nas/utils/torch_utils.py", line 526, in prepare_data_queues
    assert shuffle_seed is not None
AssertionError

**Comment by walkerning** [comment]
Hi! Many thanks, and I found that we've not updated the docs/cfgs to the public repo. I've just pushed our private updates to the public repo. I think you can get rid of the current bug by using the newest master. 

If you follow the current instructions, you would need to run the supernet training phase first, and then use the trained supernet as the architecture evaluator to search for an architecture. Note that the example configurations are a little different from what we've used in our experiments, in that `shuffle_data_before_split` is set to `false` in the provided example configurations. This is only a choice that would not influence the conclusion or the effectiveness of the framework.

As a reminder, if you want to skip the supernet training phase, and directly run the predictor-based search phase. You need to download the trained supernet checkpoints and change the file paths in the configuration files accordingly.
In that case, you also need to change `shuffle_data_before_split: false` configuration item to `shuffle_data_before_split: true`, and use the data shuffling indices file [here](https://cloud.tsinghua.edu.cn/f/fa8e252640ee4c03bd30/?dl=1). The related instructions could also be found [in this section](https://github.com/walkerning/aw_nas/tree/master/examples/research/multishot-robnas#run-supernet-adversarial-training) in the quoted note.
