### ISSUE TITLE
nasbench.api.OutOfDomainError: unsupported op none

### ISSUE THREAD

**Issue by czyczyyzc** [walkerning/aw_nas#51]
When I run awnas search examples/nasbench/nasbench-101_sa.yaml --gpu 0 --save-every 10 --train-dir /public/data1/users/ziyechen/awnas/logs/nasbench-101_sa, an error occurs:

Traceback (most recent call last):
  File "/public/data1/users/ziyechen/.conda/envs/aw_nas/bin/awnas", line 33, in <module>
    sys.exit(load_entry_point('aw-nas', 'console_scripts', 'awnas')())
  File "/public/data1/users/ziyechen/.conda/envs/aw_nas/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/public/data1/users/ziyechen/.conda/envs/aw_nas/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/public/data1/users/ziyechen/.conda/envs/aw_nas/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/data1/users/ziyechen/.conda/envs/aw_nas/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/data1/users/ziyechen/.conda/envs/aw_nas/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/public/data1/users/ziyechen/aw_nas-master/aw_nas/main.py", line 235, in search
    trainer.train()
  File "/public/data1/users/ziyechen/aw_nas-master/aw_nas/trainer/simple.py", line 293, in train
    finished_e_steps, finished_c_steps)
  File "/public/data1/users/ziyechen/aw_nas-master/aw_nas/trainer/simple.py", line 204, in _controller_update
    step_loss=step_loss))
  File "/public/data1/users/ziyechen/aw_nas-master/aw_nas/btcs/nasbench_101.py", line 706, in evaluate_rollouts
    query_res = rollout.search_space.nasbench.query(rollout.genotype)
  File "/public/data1/users/ziyechen/nasbench/nasbench/api.py", line 237, in query
    fixed_stat, computed_stat = self.get_metrics_from_spec(model_spec)
  File "/public/data1/users/ziyechen/nasbench/nasbench/api.py", line 364, in get_metrics_from_spec
    self._check_spec(model_spec)
  File "/public/data1/users/ziyechen/nasbench/nasbench/api.py", line 391, in _check_spec
    % (op, self.config['available_ops']))
nasbench.api.OutOfDomainError: unsupported op none (available ops = ['conv3x3-bn-relu', 'conv1x1-bn-relu', 'maxpool3x3'])

**Comment by TangChangcheng** [comment]
@czyczyyzc we already fix this bug by checking validation after mutation.

Thank you for your support!
